### ISSUE TITLE
Fix xone compilation issue on J3

### ISSUE THREAD

**Issue by dylan-gonzalez** [MonashNovaRover/xone#1]
@hacker1024 
> Basically you need xone, a kernel module. It doesn't compile on Linux 4.9 though, so I found a random patch on Discord to fix it (IIRC I forked xone on MonashNovaRover and made a branch with said patch). For some reason though, it still wasn't compiling on J3 even though it was fine on J1. I think J3 might be running a slightly different version of Jetson Linux.

Not exactly sure what the difference between J1 and J3 is that could be causing this issue...
> It may be worth reflashing all the Jetsons using the tx2-image-builder anyway - it's been a while since we've done any clean installs. We can also add xone to the builder probably

**Comment by Redecorating** [comment]
kernel headers were installed wrong so i copied them from J1 and then xone installed ok and i tested with victor that the rover can move with the controller
